name: Scrape status of water outages

on:
  push:
  workflow_dispatch:
  schedule:
  - cron:  '59 * * * *'

permissions:
  contents: write

jobs:
  shot-scraper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cache Oxipng
      uses: actions/cache@v3
      with:
        path: ~/.cargo/
        key: ${{ runner.os }}-cargo
    - name: Install Oxipng if it is not installed
      run: |
        which oxipng || cargo install oxipng

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-playwright

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        shot-scraper install

    - name: Scrape
      run: |
        echo "FILEPATH=images/tn2/southeastwater-tn2-$(date +%s).png" >> $GITHUB_ENV

        shot-scraper https://inyourarea.digdat.co.uk/southeastwater\?pc\=tn2 --wait 5000 -a auth.json --width 1375 --height 1100 -s '#map-container' -o "${{ env.FILEPATH }}"

    - name: Optimize PNGs
      run: |-
        oxipng -o 4 -i 0 --strip safe "${{ env.FILEPATH }}"

    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
